on: 
  push: 
    branches: [master]

jobs:
  jobs1:
    runs-on: ubuntu-latest
    steps:
      # Ligne 10 (corrigée : ajout d'un espace après le tiret)
    - name: Cstep 1
      # Ligne 11 (corrigée : l'indentation de 'run' est cruciale)
      run: echo "This is step 1 of job 1"
    - name: Checkout code
      uses: actions/checkout@v6
    - name: list files
      run: ls -la
    - name: end step
      run: echo "This is the end of job 1"
      